
# Table of numpy function/method used 

| Syntax      | function/method | Description     |
| :----:      |    :----:       |   :----:        |
| array()     |   function      |used to initialize  array of different dimentions | 
| arange(start,end,interval)    |  function       |returns an array with evenly spaced elements as per the interval.|
| linspace(start,end,nos_of_elements)    |  function         |returns an array with evenly spaced elements as per the interval.|
| logspace(start,end,nos_of_elements)      |  function         |return numbers spaced evenly on a log scale.|
| zeros(n,datatype)      |  function         |returns a new array of given shape and type, with 0's.|
| ones(n,datatype)      |  function         |returns a new array of given shape and type, with 1's.|
| dtype       |  method         |returns the data type of the array|
| view()      |  method         |used for shallow copying|
| copy()      |  method         |used for deep copying|


# INDEX

### - Types of Array
### -  numpy
> 1. Importing library
> 2. NumPy Array Indexing
> 3. NumPy Array Slicing
> 4. NumPy Data Types
> 5. copy v/s view
> 6. Ways to create array

# Types of Arrays 


**Single Dimentional Arrays** - These type of array represent only one row or one column of elements

**Multi-Dimentional Arrays** - These type of array represent more than one row and more than
one column of elements

**NOTE** - Code under section of *Types of Arrays* should not be run as it will give error. Here main motive is to make one understand how different arrays exist.
We will understand correct way to implement in further in course

####  Single Dimentional Arrays

In [38]:

marks = array( [50,60,70,80] )


#### Multi-Dimentional Arrays



In [25]:
# 2- Dimentional Arrays

# An array that has 1-D arrays as its elements is called a 2-D array.

marks1 = array([[50,60,70,80],
                [60,62,56,70],
                [71,59,80,68]])


'\nmarks1 = array([[50,60,70,80],\n                [60,62,56,70],\n                [71,59,80,68]])\n'

In [26]:
# 3- Dimentional Arrays
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

marks2 = array([[[1, 2, 3], 
                 [4, 5, 6]],
                [[1, 2, 3], 
                 [4, 5, 6]]])




'\nmarks2 = array([[[1, 2, 3], \n                 [4, 5, 6]],\n                [[1, 2, 3], \n                 [4, 5, 6]]])\n'

# numpy


1. numpy is a package that contains several classes, functions, variables etc. to deal with scientific calculations in Python.
2. numpy is useful to create and also process single and multi-dimensional arrays.
3. In addition, numpy contains a large library of mathematical functions like linear algebra functions and Fourier transforms.
4. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
5. Arrays are very frequently used in data science, where speed and resources are very important.

- To get complete help on numpy, the reader can refer to the following link at scipy.org:

  **http://docs.scipy.org/doc/numpy/reference/**

# Importing the library 

In [4]:
# to use numpy in out program we should first import numpy using 'import' keyword 

import numpy

# create single dimensional array using numpy 

arr = numpy.array([10,20,30,40,50])
print(arr)



[10 20 30 40 50]


In [5]:
import numpy as np 
"""
Here we are using 'np' as reference to numpy. 
So whenever we need to type numpy we simply use np insted
This makes typing easy
"""

arr1 = np.array([10,20,30,40,50])
print(arr1)


[10 20 30 40 50]


In [11]:
from numpy import * 

"""
This will import everything(* means all) from numpy package 
Now, we dont need to use any name to refer the objects 
or functions in our program
"""

arr2 = array([10,20,30,40,50])
print(arr2)


[10 20 30 40 50]


# NumPy Array Indexing


1. Array indexing is the same as accessing an array element.

2. You can access an array element by referring to its index number.

3. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [6]:
import numpy as np

arr3 = np.array([78,25,84,99,520])

for i in range(4):
    print(arr3[i])


78
25
84
99


In [7]:
import numpy as np

arr4 = np.array([[1,2,3,4,5], 
                 [6,7,8,9,10]])

# to print last element of senond row 

print(arr4[1][4]) # represent 1st row and 4th column of arr4
#or
print(arr4[1,-1])



10
10


In [8]:
import numpy as np

arr = np.array([
                 [[1, 2, 3], 
                 [4, 5, 6]], 
    
                [[7, 8, 9], 
                 [10, 11, 12]]])

print(arr[1, 1, 2])

12


# NumPy Array Slicing



1. Slicing refers to extracting a range of elements from the array. The format of slicing operation is given as:

2. We pass slice instead of index like this:   
>arrayname[start:end:step]       
                        
   this will print elements starting from index 'start'  upto  'end-1' 

3. If we don't pass start its considered 0

4. If we don't pass end its considered length of array in that dimension

5. If we don't pass step its considered 1

**NOTE -** 
- When negative number i is used for 'start', it should be taken as n+i. 
- When negative number j is used for  'stop', it should be taken as n+j. 
- When negative number is used for 'stepsize', the stepping goes towards 
  smaller indexes.
- n is number of elements in an array

In [9]:
from numpy import * 

a = arange(5,12)
print(a)

[ 5  6  7  8  9 10 11]


In [10]:
a1 = a[1::2]
print(a1)

[ 6  8 10]


In [11]:
a2 = a[-2:2:-1]
print(a2)

# if here step = 1 
# empty array will be printed

[10  9  8]


### ***Question ??***

If,
a3 = a[ : : ]

1. What will be a3 when print ? 
2. How to reverse the order of array a

#### Slicing 2-D Arrays


In [12]:
import numpy as np

b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(b[1, 1:4])

[7 8 9]


In [13]:
# From both elements, return index 2:
import numpy as np

b1 = b[0:2, 2]

print(b1)

[3 8]


In [14]:
#From both elements, slice index 1 to index 4 (not included), 
#this will return a 2-D array:


import numpy as np

b2 = b[0:2, 1:4]
print(b2)

[[2 3 4]
 [7 8 9]]


# NumPy Data Types


**Data Types in Python**

1. By default Python have these data types:

> - strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"  
> - integer - used to represent integer numbers. e.g. -1, -2, -3  
> - float - used to represent real numbers. e.g. 1.2, 42.42  
> - boolean - used to represent True or False.  
> - complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j  

2. Data Types in NumPy  
   NumPy has some extra data types, and refer to data types with one character,    like i for integers, u for unsigned integers etc.

3. Below is a list of all data types in NumPy and the characters used to        represent them.

> - i - integer  
> - b - boolean  
> - u - unsigned integer  
> - f - float  
> - c - complex float  
> - m - timedelta  
> - M - datetime  
> - O - object  
> - S - string  
> - U - unicode string  
> - V - fixed chunk of memory for other type ( void )  



Checking the Data Type of an Array  
The NumPy array object has a property called **dtype** that returns the data type of the array:

In [15]:
import numpy as np

arr5 = np.array(['A', 'B', 'C'])
print(arr5.dtype)

arr6 = np.array([1, 2, 3, 4])
print(arr6.dtype)


<U1
int32


# copy v/s view


In [27]:
from numpy import * 

c = array([1,2,3,4,5])
d = c 

print('memory loaction of array c:', id(c))
print('memory loaction of array c:', id(d))

memory loaction of array c: 2334466356768
memory loaction of array c: 2334466356768


1. This is a simple assignment that does not make any new copy of the array 'c'. It means, 'd' is not a new array and memory is not allocated to 'd'. 
2. Also, elements from 'c' are not copied into 'd' since there is no memory for 'd'. 
3. It means the names 'a' and 'b' are referencing same array. 
   This is called 'aliasing'. 

4. 'Aliasing' is not 'copying'. Aliasing means giving another name to the existing bbject. Hence, any modifications to the alias object will reflect in the existing object and vice versa. 

In [28]:
d[0] = 10   # modifying d

# after modification
print("c = ", c)
print("d = ", d)



c =  [10  2  3  4  5]
d =  [10  2  3  4  5]


#### Viewing an array

1. We can create another array that is same as an existing array. 
   This is done by the **view()** method. 
2. This method creates a copy of an existing array such that the new array will also contain the same elements found in the existing array. 
3. The original array and the newly created arrays will share *different memory locations.* 
4. If the newly created array is modified, the original array will also be modified since the elements in both the arrays will be like mirror images. 

In [33]:
# code for viewing an array.

import numpy as np 

e = np.arange(1,6)
f = e.view()      # ‘shallow copying’


print('memory loaction of array e:',id(e))
print('memory loaction of array f:',id(f))


f[0] = 20

print("e = ", e)
print("f = ", f)

memory loaction of array e: 2334489084992
memory loaction of array f: 2334489084112
e =  [20  2  3  4  5]
f =  [20  2  3  4  5]


#### Copying an array 

1. Suppose we want both the arrays to be independent and modifying one array should not affect another array we should go for *‘deep copying’.*

2. This is done with the help of **copy()** method. This method makes a complete copy of an existing array and its elements.

3. When the newly created array is modified, it will not affect the existing array or vice versa. There will not be any connection between the elements of the two arrays.


In [35]:
# code for copying an array.

import numpy as np 
 
g = np.arange(10)
h = g.copy()      # 'deep copy'

print('memory loaction of array g:',id(g))
print('memory loaction of array h:',id(h))


h[0] = 25

print("g = ",g)
print("h = ",h)

memory loaction of array g: 2334489086992
memory loaction of array h: 2334489085872
g =  [0 1 2 3 4 5 6 7 8 9]
h =  [25  1  2  3  4  5  6  7  8  9]


# Ways to create array 

- Creating arrays in numpy can be done in several ways. Some of the important ways are:
> 1. using array() function 
> 2. using linspace() function
> 3. using logspace() function
> 4. using arange() funtion 
> 5. using zeros() and ones() function

**Creating Arrays using linspace**

1. The linspace function is used to create an array with evenly spaced points between a starting point and ending point. The form of the linspace() function is:

> linspace(start, stop, n)

2. start' represents the starting element and 'stop' represents the ending element. 'n' is an integer that represents the number of parts the elements should be divided. If 'n' is omitted, then it is taken as 50. Let's take one example to understand this.


In [20]:
import numpy as np 

i= np.linspace(0, 20,5)
print(i)

[ 0.  5. 10. 15. 20.]


**Creating Arrays using logspace**

1. The logspace() function is similar to linspace(). 
2. The linspace() function produces the evenly spaced points. 
   Similarly, logspace() produces evenly spaced points on a logarithmically spaced scale. 
3. The logspace() function is used in the following format: 
> logspace(start, stop, n)

4. The logspace() function starts at a value which is 10 to the power of 'start' and ends at a value which is 10 to the power of 'stop'. 
5. If 'n' is not specified, then its value is taken as 50. 

For example, if we write:

In [21]:
j = logspace(1, 4, 5)
print(j)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]


**Creating Arrays using zeros() and ones() function**

1. We can use zeros() function to create an array with all elements as 0 

2. Similarly, We can use ones() function to create an array with all elements as 1 

*syntax -*

> zeros(n,datatype)  
> ones(n,datatype)

In [36]:
k = zeros(3,int)
l = ones(5 , float)

print(k)
print(l)

[0 0 0]
[1. 1. 1. 1. 1.]
