### Importing NumPy

In [1]:
import numpy as np

## Array Math

### Functions Used in this Section

| Function     | Description/Use | Parameter(s) | Return Value(s) |
| ----------- | ----------- | ----------- | ----------- |
| numpy.array_equal(a1, a2, equal_nan=False)      |   Checks the equality of two arrays   | a1, a2 = Arrays to be compared;<br> equal_nan = Decides whether to compare NaNs as equal       | True if two arrays have the same shape and elements, <br>False otherwise       |
| numpy.sin(x)   | Calculates element-wise trigonometric sine       | x is the array      | Array of sine of each element  |
| numpy.log(x)   | Calculates element-wise natural logarithm       | x is the array      | Array of natural logarithm of each element  |
| numpy.exp(x)   | Calculates element-wise exponential       | x is the array      | Array of exponential of each element  |
| numpy.sqrt(x)   | Calculates element-wise non-negative square root       | x is the array      | Array of positive square root of each element  |
| numpy.cos(x)   | Calculates element-wise trigonometric cosine       | x is the array      | Array of cosine of each element  |
| numpy.isnan(x)   | Checks for NaN element-wise       | x is the array      | Boolean array : For each element, if it is NaN, then True, else False  |
| numpy.reshape(a, newshape)   | Gives a new shape to an array without changing its data      | a = Array;<br> newshape = Shape tuple      | Reshaped array  |
| numpy.ravel(a)   | Returns a contiguous flattened array     | a = Array     | A 1-D array containing the elements of the input |
| numpy.resize(a, newshape)   | Returns a new array with the specified shape.<br>If the new array is larger than the original array,<br> then the new array is filled with repeated copies of a.<br> Note that this behavior is different from a.resize(new_shape)<br> which fills with zeros instead of repeated copies of a.     | a = Array;<br> newshape = Shape tuple     | Array with the specified shape |
| numpy.transpose(a, axes=None)   | Reverses or permutes the axes of an array; returns the modified array       | a = Array;<br> axes = Tuple/list of axes to be reversed/permutated      | a with its axes permuted  |
| numpy.sum(a, axis=None)   | Calculates sum of array elements over a given axis       | a = Array;<br> axes = Tuple of axis or axes along which a sum is performed     | Array of sums with the same shape as a,<br> with the specified axis removed  |
| numpy.dot(a, b)   | Calculates dot product of two arrays      | a, b = Arrays     | Returns the dot product of a and b<br> If a and b are both scalars<br> or both 1-D arrays then a scalar is returned;<br> otherwise an array is returned  |
| ndarray.min(axis=None)   | Calculates the minimum along a given axis       | axis = Axis along which minimum is to be found     | The minimum value along a given axis  |
| ndarray.max(axis=None)   | Calculates the maximum along a given axis       | axis = Axis along which maximum is to be found     | The maximum value along a given axis  |
| numpy.mean(a, axis=None) | Computes the arithmetic mean along the specified axis | a = Array;<br> axis = Axis or axes along which the means are computed | Array containing the mean values |
| numpy.median(a, axis=None) | Computes the median along the specified axis | a = Array;<br> axis = Axis or axes along which the medians are computed | Array containing the median values |
| numpy.std(a, axis=None) | Computes the standard deviation along the specified axis | a = Array;<br> axis = Axis or axes along which the standard deviations are computed | Array containing the standard deviation |
| numpy.sort(a, axis=-1) | Sorts the array | a = Array;<br> axis = Axis along which to sort | Sorted copy of array  |

### Numerical Operations on Arrays

Element-wise operation is performed.

#### Creating NumPy arrays a and b

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 5, 1, 6])

#### Element-wise Operations

In [3]:
a + 1

array([2, 3, 4, 5])

In [4]:
a * 5

array([ 5, 10, 15, 20])

In [5]:
3**a

array([ 3,  9, 27, 81])

In [6]:
a - b

array([-2, -3,  2, -2])

In [7]:
a * b

array([ 3, 10,  3, 24])

In [8]:
a > b

array([False, False,  True, False])

In [9]:
a += b
a

array([ 4,  7,  4, 10])

To compare the whole array for equality, use array_equal().

In [10]:
np.array_equal(a, b)

False

#### Mathematical Functions

Mathematical functions work on each element.

In [11]:
np.sin(a)

array([-0.7568025 ,  0.6569866 , -0.7568025 , -0.54402111])

In [12]:
np.log(a)

array([1.38629436, 1.94591015, 1.38629436, 2.30258509])

In [13]:
np.exp(a)

array([   54.59815003,  1096.63315843,    54.59815003, 22026.46579481])

In [14]:
np.sqrt(a)

array([2.        , 2.64575131, 2.        , 3.16227766])

In [15]:
np.cos(a)

array([-0.65364362,  0.75390225, -0.65364362, -0.83907153])

In [16]:
np.isnan(a)

array([False, False, False, False])

### Array Attributes

In [17]:
print(a.ndim) # Prints the number of dimensions
print(a.shape) # Prints the shape
print(a.dtype) # Prints the datatype

1
(4,)
int64


### Reshaping Arrays

In [18]:
a.reshape(2,-1) # Reshape array into a matrix with 2 rows

array([[ 4,  7],
       [ 4, 10]])

In [19]:
c = np.array([[1, 2, 3, 4], [4, 5, 6, -1], [7, 8, 9, 12]])

In [20]:
c.reshape(6, 2) # Reshape array into a matrix of size 6 x 2

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6, -1],
       [ 7,  8],
       [ 9, 12]])

In [21]:
c.ravel() # To give a contiguous flattened array

array([ 1,  2,  3,  4,  4,  5,  6, -1,  7,  8,  9, 12])

In [22]:
d = np.array([5, 6, 7, 8])
np.resize(d, (8,2))

array([[5, 6],
       [7, 8],
       [5, 6],
       [7, 8],
       [5, 6],
       [7, 8],
       [5, 6],
       [7, 8]])

### Transpose

In [23]:
c.T

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4, -1, 12]])

In [24]:
c.transpose((1, 0)) # Reverses or permutes the axes of the array. The axes here are 0 and 1

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4, -1, 12]])

### Sum of Arrays

In [25]:
np.sum(a)

25

In [26]:
a.sum()

25

In [27]:
c.sum(axis = 0) # Sum by columns

array([12, 15, 18, 15])

In [28]:
c.sum(axis = 1) # Sum by rows

array([10, 14, 36])

In [29]:
c.sum() # Total sum of all elements

60

### Dot Product of Two Matrices

In [30]:
e = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
f = np.array([[4, 5], [1, 3], [8, 2]])
e.dot(f)

array([[ 30,  17],
       [ 69,  47],
       [108,  77]])

### Statistics in Arrays

In [31]:
e.min()

1

In [32]:
e.max()

9

In [33]:
e.mean()

5.0

In [34]:
np.median(f)

3.5

In [35]:
f.std()

2.266911751455907

### Sorting

In [36]:
np.sort(f, axis = 0) # Sorts each column separately

array([[1, 2],
       [4, 3],
       [8, 5]])

##NumPy Documentation
Link : [Go here for User Guide and API Reference](https://numpy.org/doc/)
