In [91]:
import numpy as np

##Array Math

###Numerical Operations on Arrays

In [92]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 5, 1, 6])

Element-wise operation is performed.

In [93]:
a + 1

array([2, 3, 4, 5])

In [94]:
a * 5

array([ 5, 10, 15, 20])

In [95]:
3**a

array([ 3,  9, 27, 81])

In [96]:
a - b

array([-2, -3,  2, -2])

In [97]:
a * b

array([ 3, 10,  3, 24])

In [98]:
a > b

array([False, False,  True, False])

In [99]:
a += b
a

array([ 4,  7,  4, 10])

To compare the whole array, use array_equal()

In [100]:
np.array_equal(a, b)

False

Mathematical functions work on each element.

In [101]:
np.sin(a)

array([-0.7568025 ,  0.6569866 , -0.7568025 , -0.54402111])

In [102]:
np.log(a)

array([1.38629436, 1.94591015, 1.38629436, 2.30258509])

In [103]:
np.exp(a)

array([   54.59815003,  1096.63315843,    54.59815003, 22026.46579481])

In [104]:
np.sqrt(a)

array([2.        , 2.64575131, 2.        , 3.16227766])

In [105]:
np.cos(a)

array([-0.65364362,  0.75390225, -0.65364362, -0.83907153])

In [106]:
np.isnan(a)

array([False, False, False, False])

Array Attributes

In [107]:
print(a.ndim) # Prints the number of dimensions
print(a.shape) # Prints the shape
print(a.dtype) # Prints the datatype

1
(4,)
int64


Reshaping Arrays

In [108]:
a.reshape(2,-1) # Reshape array into a matrix with 2 rows

array([[ 4,  7],
       [ 4, 10]])

In [109]:
c = np.array([[1, 2, 3, 4], [4, 5, 6, -1], [7, 8, 9, 12]])

In [110]:
c.reshape(6, 2) # Reshape array into a matrix of size 6 x 2

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6, -1],
       [ 7,  8],
       [ 9, 12]])

In [111]:
c.ravel() # To give a contiguous flattened array

array([ 1,  2,  3,  4,  4,  5,  6, -1,  7,  8,  9, 12])

In [112]:
d = np.array([5, 6, 7, 8])
np.resize(d, (8,2))

array([[5, 6],
       [7, 8],
       [5, 6],
       [7, 8],
       [5, 6],
       [7, 8],
       [5, 6],
       [7, 8]])

Transpose

In [113]:
c.T

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4, -1, 12]])

In [114]:
c.transpose((1, 0)) # Reverses or permutes the axes of the array. The axes here are 0 and 1

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4, -1, 12]])

Sum of Arrays

In [115]:
np.sum(a)

25

In [116]:
a.sum()

25

In [117]:
c.sum(axis = 0) # Sum by columns

array([12, 15, 18, 15])

In [118]:
c.sum(axis = 1) # Sum by rows

array([10, 14, 36])

In [119]:
c.sum() # Total sum of all elements

60

Dot Product of Two Matrices

In [120]:
e = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
f = np.array([[4, 5], [1, 3], [8, 2]])
e.dot(f)

array([[ 30,  17],
       [ 69,  47],
       [108,  77]])

Statistics in Arrays

In [121]:
e.min()

1

In [122]:
e.max()

9

In [123]:
e.mean()

5.0

In [124]:
np.median(f)

3.5

In [125]:
f.std()

2.266911751455907

Sorting

In [126]:
np.sort(f, axis = 0) # Sorts each column separately

array([[1, 2],
       [4, 3],
       [8, 5]])

##NumPy Documentation
Link : [Go here for User Guide and API Reference](https://numpy.org/doc/)
